spring:
  cloud:
      refresh:
        refreshable: none
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://192.168.99.100:33306/chaos?useSSL=false&allowPublicKeyRetrieval=true
    username: chaos
    password: chaos123
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  profiles:
    active: chaos-monkey
      
server:
  port: 8092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
chaos:
  monkey:
    enabled: true
    assaults:
      level: 7
      latencyRangeStart: 1000
      latencyRangeEnd: 10000
      exceptionsActive: false
      killApplicationActive: true
    watcher:
      repository: true
      restController: true
      
management:
  endpoint:
    chaosmonkey:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,chaosmonkey